module.exports = {
  data: {
    name: "joke",
    description: "Conta uma piada brasileira engraçada (offline)"
  },

  async execute(interaction, client) {
    const piadas = [
      "Por que o milho é malcriado? Porque ele dá milho verde!",
      "Qual é o contrário de papelada? Papel fora da caixa!",
      "Por que o pneu não sobe na árvore? Porque ele é de borracha!",
      "O que o pato disse para a pata? Vem Quá!",
      "Por que o jacaré tirou o filho da escola? Porque ele réptil de ano!",
      "Por que a aranha é o animal mais carente? Porque ela é um aracnídeo!",
      "O que é um pontinho amarelo no céu? Um fubá voador!",
      "Qual é o cúmulo do azar? Ser atropelado por um carro funerário!",
      "Por que a vaca foi para o espaço? Para se encontrar com a via-láctea!",
      "O que o tomate foi fazer no banco? Tirar extrato!",
      "Por que o coelho atravessou a estrada? Para mostrar que ele tinha coragem!",
      "Qual o queijo mais triste? O queijo-de-chorar.",
      "Por que o computador foi ao médico? Porque estava com vírus!",
      "O que o pato falou quando viu o papagaio? Quá, quá, qui, qui!",
      "Por que o livro foi ao médico? Porque estava com muitas páginas em branco!",
      "O que o relógio disse para o tempo? Para de me pressionar!",
      "Por que o peixe não gosta de jogar cartas? Porque ele tem medo do tubarão!",
      "O que o zero disse para o oito? Que cinto maneiro!",
      "Por que o menino levou uma escada para a escola? Porque a aula era no alto nível!",
      "Qual é o animal que gosta de festa? O gato, porque ele adora um miado!",
      "O que é verde e fica no canto da sala? O canto verde!",
      "Por que a laranja se suicidou? Porque estava se sentindo espremida!",
      "O que é um pontinho vermelho no meio do mar? Um peixe com dor de dente!",
      "Por que a vaca foi para o espaço? Para se encontrar com a via-láctea!",
      "O que o pão falou para a manteiga? Você me completa!",
      "Qual é a planta mais divertida? A planta que dá risada: a risada!",
      "Por que o tomate foi ao banco? Para tirar extrato!",
      "Qual é o cúmulo da velocidade? Correr atrás do vento e não alcançar!",
      "Por que o cavalo foi ao bar? Para tomar uma água de potro!",
      "O que o papel falou para a caneta? Você me faz escrever!",
      "Por que o elefante não usa computador? Porque ele tem medo do mouse!",
      "Qual é o animal que come com o rabo? Todos, porque nenhum tira o rabo para comer!",
      "Por que a abelha sempre leva bronca? Porque ela é uma zanguinha!",
      "O que o vento falou para o fogo? Apaga essa vela!",
      "Por que o cachorro entrou na igreja? Para virar um cachorro-quente!",
      "Qual é o cereal preferido do fantasma? O sucrilhos!",
      "Por que o livro de matemática terminou com a namorada? Porque tinha muitos problemas!",
      "O que a faca disse para o pão? Você me corta o coração!",
      "Por que o gafanhoto é péssimo em matemática? Porque ele só sabe pular as contas!",
      "O que o cachorro falou para o poste? Nossa, como você está duro!",
      "Por que o cavalo foi para a escola? Para aprender a cavalgar!",
      "Qual é a comida que liga e desliga? O Strog-ON e OFF!",
      "Por que o sapo é tão feliz? Porque ele come o que pula!",
      "O que é um pontinho azul na piscina? Uma aguinha com azulzinho!",
      "Por que o pinguim não gosta do calor? Porque ele derrete!",
      "O que a luz falou para a sombra? Você me segue demais!",
      "Qual é o animal mais esquecido? O elefante, porque tem memória de elefante!",
      "Por que a vaca foi para o espaço? Para se encontrar com a via-láctea!",
      "O que o sol falou para a lua? Você me ilumina a noite!",
      "Por que o jacaré tirou o filho da escola? Porque ele réptil de ano!",
      "O que o pato disse para a pata? Vem Quá!",
      "Por que o livro foi ao médico? Porque estava com muitas páginas em branco!",
      "Qual é o cúmulo do azar? Ser atropelado por um carro funerário!",
      "Por que o tomate foi fazer no banco? Tirar extrato!",
      "Qual o cúmulo do esquecimento? Esquecer a senha do Wi-Fi!",
      "Por que o cavalo entrou no bar? Porque estava a fim de um 'copinho'!",
      "O que a impressora falou para o papel? Eu estou sentindo sua falta!",
      "Por que o relógio foi preso? Porque ele deu um tempo!",
      "Qual o peixe que caiu do décimo andar? Aaaaarraia!",
      "Por que o jacaré é mais feliz que o crocodilo? Porque o jacaré é 'mais alegre'!",
      "O que o tijolo falou para o outro? Há um ciumento entre nós!",
      "Qual é o peixe que gosta de matemática? O peixe 'conta-tudo'!",
      "Por que o lápis foi ao médico? Porque estava sem ponta!",
      "O que o boi falou para a vaca no campo? Te amo, meu amor!",
      "Qual é o cúmulo da preguiça? Levantar da cama para desligar o despertador e voltar a dormir!",
      "Por que a galinha atravessou a rua? Para chegar do outro lado!",
      "O que o chocolate disse para o leite? Sem você eu fico derretido!",
      "Qual o legume que não se importa com nada? O quiabo!",
      "Por que o coelho foi ao psicólogo? Porque estava se sentindo 'descabelado'!",
      "O que o pão falou para a manteiga? Você me deixa mais gostoso!",
      "Por que o gato mia? Porque o cachorro late!",
      "Qual é o animal mais antigo? A zebra, porque está em preto e branco!",
      "Por que o rato roeu a roupa do rei de Roma? Porque ele era um rato rebelde!",
      "O que o vento disse para o cabelo? Para de bagunçar meu dia!",
      "Qual o cúmulo do desespero? Entrar numa sala cheia de Wi-Fi e não pegar sinal!",
      "Por que a aranha é ótima na internet? Porque ela conhece todas as teias!",
      "O que o leite falou para o café? Você me deixa mais forte!",
      "Qual é o cúmulo da sorte? Ganhar na loteria e perder o bilhete!",
      "Por que o elefante não usa computador? Porque ele tem medo do mouse!",
      "O que a formiga disse para o elefante? Você é um grande amigo!",
      "Qual é o cúmulo da força? Levantar um caminhão e ainda abrir a porta para o motorista!",
      "Por que o cavalo não gosta de futebol? Porque ele tem medo do gol!",
      "O que o feijão disse para o arroz? Juntos somos melhores!",
      "Qual é a cor preferida do vampiro? O vermelho sangue!",
      "Por que o sapo é feliz? Porque ele sabe pular os problemas!",
      "O que a água falou para o fogo? Eu te apago, mas você me acende!",
      "Qual é o carro favorito do gato? O 'miau-dai'!",
      "Por que o peixe é inteligente? Porque ele nada nas ideias!",
      "O que o celular falou para a tomada? Você me recarrega!",
      "Qual é o cúmulo da velocidade? Correr atrás do vento e não alcançar!",
      "Por que o passarinho canta? Porque ele está feliz!",
      "O que a lua disse para o sol? Você é meu brilho da noite!",
      "Qual é o maior medo do computador? A tela azul da morte!",
      "Por que a planta foi ao médico? Porque estava se sentindo mal!",
      "O que o botão disse para o casaco? Fecha essa boca!",
      "Qual é o cúmulo da inteligência? Entender tudo isso que eu falei!",
       "Por que o jacaré tirou o filho da escola? Porque ele réptil de ano!",
        "O que o pato disse para a pata? Vem Quá!",
        "Qual é o animal mais antigo? A zebra, porque está em preto e branco!",
        "Por que o computador foi ao médico? Porque estava com vírus!",
        "O que o zero disse para o oito? Que cinto maneiro!",
        "Por que o livro de matemática terminou com a namorada? Porque tinha muitos problemas!",
        "Qual é o cúmulo da sorte? Ganhar na loteria e perder o bilhete!",
        "Por que o sapo é feliz? Porque ele sabe pular os problemas!",
        "O que o tomate foi fazer no banco? Tirar extrato!",
        "Qual é o cúmulo da preguiça? Levantar da cama para desligar o despertador e voltar a dormir!",
        "Por que o gato mia? Porque o cachorro late!",
        "O que a impressora falou para o papel? Eu estou sentindo sua falta!",
        "Qual é o cereal preferido do fantasma? O sucrilhos!",
        "Por que a vaca foi para o espaço? Para se encontrar com a via-láctea!",
        "O que o pão falou para a manteiga? Você me completa!",
        "Qual é o cúmulo da velocidade? Correr atrás do vento e não alcançar!",
        "Por que o coelho atravessou a estrada? Para mostrar que ele tinha coragem!",
        "O que o relógio disse para o tempo? Para de me pressionar!",
        "Por que o pneu não sobe na árvore? Porque ele é de borracha!",
        "Qual o legume que não se importa com nada? O quiabo!",
        "Por que o elefante não usa computador? Porque ele tem medo do mouse!",
        "O que o boi falou para a vaca no campo? Te amo, meu amor!",
        "Por que a aranha é ótima na internet? Porque ela conhece todas as teias!",
        "Qual é o maior medo do computador? A tela azul da morte!",
        "O que o botão disse para o casaco? Fecha essa boca!",
        "Por que a planta foi ao médico? Porque estava se sentindo mal!",
        "Qual é o cúmulo da força? Levantar um caminhão e ainda abrir a porta para o motorista!",
        "Por que o passarinho canta? Porque ele está feliz!",
        "O que o celular falou para a tomada? Você me recarrega!",
        "Por que a laranja se suicidou? Porque estava se sentindo espremida!",
        "O que a luz falou para a sombra? Você me segue demais!",
        "Qual é o cúmulo do azar? Ser atropelado por um carro funerário!",
        "O que o vento falou para o fogo? Apaga essa vela!",
        "Qual é o animal mais esquecido? O elefante, porque tem memória de elefante!",
        "Por que o lápis foi ao médico? Porque estava sem ponta!",
        "O que o gafanhoto é péssimo em matemática? Porque ele só sabe pular as contas!",
        "Por que o cachorro entrou na igreja? Para virar um cachorro-quente!",
        "Qual é o peixe que caiu do décimo andar? Aaaaarraia!",
        "Por que o cavalo não gosta de futebol? Porque ele tem medo do gol!",
        "O que o feijão disse para o arroz? Juntos somos melhores!",
        "Qual é a cor preferida do vampiro? O vermelho sangue!",
        "Por que o gato é tão engraçado? Porque ele adora uma comédia!",
        "O que a formiga disse para o elefante? Você é um grande amigo!",
        "Qual é o cúmulo do desespero? Entrar numa sala cheia de Wi-Fi e não pegar sinal!",
        "Por que o livro foi ao médico? Porque estava com muitas páginas em branco!",
      "Por que o milho é malcriado? Porque ele dá milho verde!",
      "Qual é o contrário de papelada? Papel fora da caixa!",
      "Por que o pneu não sobe na árvore? Porque ele é de borracha!",
      "O que o pato disse para a pata? Vem Quá!",
      "Por que o jacaré tirou o filho da escola? Porque ele réptil de ano!",
      "Por que a aranha é o animal mais carente? Porque ela é um aracnídeo!",
      "O que é um pontinho amarelo no céu? Um fubá voador!",
      "Qual é o cúmulo do azar? Ser atropelado por um carro funerário!",
      "Por que a vaca foi para o espaço? Para se encontrar com a via-láctea!",
      "O que o tomate foi fazer no banco? Tirar extrato!",
      "Por que o coelho atravessou a estrada? Para mostrar que ele tinha coragem!",
      "Qual o queijo mais triste? O queijo-de-chorar.",
      "Por que o computador foi ao médico? Porque estava com vírus!",
      "O que o pato falou quando viu o papagaio? Quá, quá, qui, qui!",
      "Por que o livro foi ao médico? Porque estava com muitas páginas em branco!",
      "O que o relógio disse para o tempo? Para de me pressionar!",
      "Por que o peixe não gosta de jogar cartas? Porque ele tem medo do tubarão!",
      "O que o zero disse para o oito? Que cinto maneiro!",
      "Por que o menino levou uma escada para a escola? Porque a aula era no alto nível!",
      "Qual é o animal que gosta de festa? O gato, porque ele adora um miado!",
      "O que é verde e fica no canto da sala? O canto verde!",
      // +180 piadas fictícias ou reais aqui para completar até 200...
      "Por que a laranja se suicidou? Porque estava se sentindo espremida!",
      "O que é um pontinho vermelho no meio do mar? Um peixe com dor de dente!",
      "Por que a vaca foi para o espaço? Para se encontrar com a via-láctea!",
      "O que o pão falou para a manteiga? Você me completa!",
      "Qual é a planta mais divertida? A planta que dá risada: a risada!",
      "Por que o tomate foi ao banco? Para tirar extrato!",
      "Qual é o cúmulo da velocidade? Correr atrás do vento e não alcançar!",
      "Por que o cavalo foi ao bar? Para tomar uma água de potro!",
      "O que o papel falou para a caneta? Você me faz escrever!",
      "Por que o elefante não usa computador? Porque ele tem medo do mouse!",
      "Qual é o animal que come com o rabo? Todos, porque nenhum tira o rabo para comer!",
      "Por que a abelha sempre leva bronca? Porque ela é uma zanguinha!",
      "O que o vento falou para o fogo? Apaga essa vela!",
      "Por que o cachorro entrou na igreja? Para virar um cachorro-quente!",
      "Qual é o cereal preferido do fantasma? O sucrilhos!",
      "Por que o livro de matemática terminou com a namorada? Porque tinha muitos problemas!",
      "O que a faca disse para o pão? Você me corta o coração!",
      "Por que o gafanhoto é péssimo em matemática? Porque ele só sabe pular as contas!",
      "O que o cachorro falou para o poste? Nossa, como você está duro!",
      "Por que o cavalo foi para a escola? Para aprender a cavalgar!",
       "Por que o menino levou uma escada para a escola? Porque a aula era no alto nível!",
        "Qual é o animal que gosta de festa? O gato, porque ele adora um miado!",
        "O que é verde e fica no canto da sala? O canto verde!",
        "Por que a laranja se suicidou? Porque estava se sentindo espremida!",
        "O que é um pontinho vermelho no meio do mar? Um peixe com dor de dente!",
        "Qual é a planta mais divertida? A planta que dá risada: a risada!",
        "Por que o cavalo foi ao bar? Para tomar uma água de potro!",
        "O que o papel falou para a caneta? Você me faz escrever!",
        "Qual é o animal que come com o rabo? Todos, porque nenhum tira o rabo para comer!",
        "Por que a abelha sempre leva bronca? Porque ela é uma zanguinha!",
        "O que o vento falou para o fogo? Apaga essa vela!",
        "Por que o cachorro entrou na igreja? Para virar um cachorro-quente!",
        "Qual é o cereal preferido do fantasma? O sucrilhos!",
        "Por que o livro de matemática terminou com a namorada? Porque tinha muitos problemas!",
        "O que a faca disse para o pão? Você me corta o coração!",
        "Por que o gafanhoto é péssimo em matemática? Porque ele só sabe pular as contas!",
        "O que o cachorro falou para o poste? Nossa, como você está duro!",
        "Por que o cavalo foi para a escola? Para aprender a cavalgar!",
        "Por que o jacaré não usa GPS? Porque ele sempre réptil!",
        "Por que o gato não gosta de água? Porque ele não quer perder o estilo!",
        "O que a lua disse para o sol? Você me ilumina!",
        "Por que o celular foi ao médico? Porque ele estava com bateria fraca!",
        "O que o sapato falou para o chinelo? Você está sempre de férias!",
        "Qual é o cúmulo da preguiça? Dormir em pé!",
        "O que o peixe falou para o siri? Sai da frente, estou passando!",
        "Por que o telefone foi preso? Porque ele estava grampeado!",
        "Qual é o cúmulo da distração? Esquecer o próprio nome!",
        "O que o elevador disse para a escada? Você está sempre subindo na vida!",
        "Por que o semáforo não gosta de piadas? Porque ele sempre para no vermelho!",
        "Qual é o rei dos queijos? O reiqueijão!",
        "O que o sol falou para a lua? Deixa eu brilhar um pouco!",
        "Por que o papel foi ao psicólogo? Porque estava em branco!",
        "O que o trem disse para o trilho? Sempre posso contar com você!",
        "Por que o sorvete não gosta de sol? Porque ele derrete de vergonha!",
        "O que o ventilador disse para o ar-condicionado? Você é frio demais!",
        "Por que o espelho nunca mente? Porque ele reflete!",
        "O que o copo disse para a garrafa? Me enche de alegria!",
        "Por que o bolo foi ao médico? Porque estava meio recheado!",
        "O que a chuva falou para o chão? Me aguenta aí!",
        "Qual o cúmulo da economia? Usar o mesmo chiclete por uma semana!",
        "Por que o travesseiro não gosta de conversa? Porque ele prefere o silêncio da noite!",
        "O que o leite disse para o café? Juntos somos mais fortes!",
        "Por que o balde foi ao psicólogo? Porque estava cheio!",
        "O que o chinelo disse para o sapato? Você anda muito formal!",
        "Qual é o cúmulo da força? Abrir um pote de vidro só com o olhar!",
        "Por que o avião nunca se perde? Porque ele voa nas nuvens!",
        "O que o chocolate disse para a bala? Você é muito dura!",
        "Por que a árvore não usa internet? Porque ela já está enraizada!",
        "O que o carro disse para a gasolina? Sem você não vou a lugar nenhum!",
        "Por que o lápis terminou com a borracha? Porque ela apagava tudo que ele fazia!",
        "O que o gelo disse para o freezer? Você é tão frio!",
        "Por que o rádio não gosta de TV? Porque ela sempre quer aparecer!",
        "O que o sanduíche disse para o hambúrguer? Você é muito recheado!",
        "Por que a vela não gosta de vento? Porque ele a apaga!",
        "O que o peixe disse para a rede? Não me pega!",
        "Por que o ônibus não gosta de atrasos? Porque ele perde o ponto!",
        "O que o botão falou para o zíper? Vamos fechar essa conversa!",
        "Por que o quadro foi para o museu? Para se eternizar!",
        "O que o celular disse para o carregador? Você me completa!",
        "Por que o computador sempre fica cansado? Porque ele trabalha em bytes!",
        "O que o chocolate disse para o sorvete? Você é tão frio, mas eu te derreto!",
        "Por que o gelo não gosta de calor? Porque ele perde a forma!",
        "O que o dente falou para o outro? Vamos trabalhar juntos na mastigação!",
        "Por que a girafa tem o pescoço grande? Porque a cabeça dela é longe do coração!",
        "O que a água disse para o vinho? Você sempre se destaca nas festas!",
        "Por que o ônibus nunca mente? Porque ele sempre segue a linha!",
        "O que o espelho disse para o vaidoso? Eu te vejo todo dia!",
        "Por que o chapéu foi ao psicólogo? Porque ele estava perdendo a cabeça!",
        "O que o papel falou para a impressora? Estou pronto para ser preenchido!",
        "Por que o trem não gosta de piadas? Porque ele já tem muita linha!",
        "O que o óculos disse para o rosto? Eu te vejo melhor que ninguém!",
        "Por que a caneta terminou com o papel? Porque ele era muito vazio!",
        "O que o café disse para o açúcar? Você adoça minha vida!",
        "Por que o peixe não gosta de praia? Porque lá ele não consegue nadar!",
        "O que a árvore disse para o vento? Você me balança, mas não me derruba!",
        "Por que o caminhão foi preso? Porque ele carregava peso demais!",
        "O que o livro disse para o leitor? Abra-me e descubra histórias!"
    ];

    const piadaAleatoria = piadas[Math.floor(Math.random() * piadas.length)];
    await interaction.reply(piadaAleatoria);
  }
};
